### ISSUE TITLE
Can't write and read from a socket at the same time

### ISSUE THREAD

**Issue by marcomorain** [jnr/jnr-unixsocket#14]
I've writing a Clojure wrapper for [Watchman](https://github.com/facebook/watchman) at [marcomorain/clj-watchman](https://github.com/marcomorain/clj-watchman) using jnr-unixsocket, and I've run into a problem that I was hoping you could help with @headius.

Watchman is a program that allows the user to set a watch on a directory, and it will alert the user when a file has changed.

You issue commands to Watchman by writing commands, formatted as JSON followed by a newline, into a unix socket, and then you can read results back, as JSON, from the socket. In this simple use-case the command and result are issued and returned in lockstep, and everything works fine.

Things get more complicated once you add a "watch" to a directory. When any file in the directory is modified, Watchman will write an event to the socket. So I set up a thread to call read on the socket in a loop to listen for these events. From my main thread I then write commands into the socket. My background thread reads results and will take the appropriate action.

The problem is that this causes a deadlock – my reader thread starts, and calls read on the socket:

```
"Thread-7" #18 daemon prio=5 os_prio=31 tid=0x00007ffacec91000 nid=0x3307 runnable [0x0000000130436000]
   java.lang.Thread.State: RUNNABLE
	at com.kenai.jffi.Foreign.invokeN3O1(Native Method)
	at com.kenai.jffi.Invoker.invokeN3(Invoker.java:1061)
	at jnr.enxio.channels.Native$LibC$jnr$ffi$1.read(Unknown Source)
	at jnr.enxio.channels.Native.read(Native.java:95)
	at jnr.enxio.channels.NativeSocketChannel.read(NativeSocketChannel.java:70)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
	- locked <0x0000000772292ff8> (a java.lang.Object)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	- locked <0x00000007722bfe28> (a sun.nio.ch.ChannelInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000007722bf818> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000007722bf818> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at com.marcomorain.watchman$read_response.invoke(watchman.clj:15)
	at com.marcomorain.watchman$connect$fn__2408.invoke(watchman.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

This is doing a blocking read as intended. No commands have been issues, so there are no responses, so this thread blocks. This is correct behaviour.

Next I issue a command on my main thread. This tries to acquire a lock on the same socket, and I get deadlock:

```
"nREPL-worker-0" #16 daemon prio=5 os_prio=31 tid=0x00007ffacde14800 nid=0x5d03 waiting for monitor entry [0x000000012f98e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.nio.channels.Channels.writeFully(Channels.java:96)
	- waiting to lock <0x0000000772292ff8> (a java.lang.Object)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	- locked <0x00000007722b8f30> (a java.nio.channels.Channels$1)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	- locked <0x00000007722b92a8> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	- locked <0x00000007722b92a8> (a java.io.OutputStreamWriter)
	at java.io.PrintWriter.flush(PrintWriter.java:320)
	- locked <0x00000007722b9280> (a java.io.BufferedWriter)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at com.marcomorain.watchman$write_command.invoke(watchman.clj:21)
	at com.marcomorain.watchman$execute_command.invoke(watchman.clj:26)
	at com.marcomorain.watchman$log_level.invoke(watchman.clj:69)
	at user$eval2419.invoke(form-init1868161862316182594.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6666)
	at clojure.core$eval.invoke(core.clj:2927)
	at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
	at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
	at clojure.main$repl$fn__6634.invoke(main.clj:257)
	at clojure.main$repl.doInvoke(main.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__881.invoke(interruptible_eval.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:51)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__923$fn__926.invoke(interruptible_eval.clj:183)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__916.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

You can see both threads are locked on the object at `0x0000000772292ff8`.

Do you have any suggestions on how to work past this? – Is there a way to read from the socket without blocking writes?

Thanks in advance for any help you can offer!

The callstacks show the state of my code as of this commit: https://github.com/marcomorain/clj-watchman/tree/e6137c0b565541132ff9a58d9f30a092637b3976

**Comment by headius** [comment]
Sorry for the delay on this...I only recently fixed my mail so I'd see JNR github traffic :-\

It appears that these locks are in the NIO subsystem and may not be easy for us to eliminate. I do notice that you're using the stream wrappers from JDK, which appear to have many of their own locks. If you need to be doing concurrent IO, wouldn't it be best to go directly to the Channel? I don't know if that would fix this overall problem, but it would eliminate a number of locks from concern.

Looking again at the locks, I'm wondering if the one you're concerned about would be avoided if you didn't use the wrapper. StreamEncoder appears to follow a locky path through NIO subsystem, and doesn't even hit our channel in this trace.

**Comment by headius** [comment]
Dig into this for 0.14. Can you help? Still out there?

**Comment by marcomorain** [comment]
Hi! I'm still out here 😀

I have not touched the project since opening this, so this issue doesn't really affect me. 

Let's close this issue, and if I get time I can try your suggestions and re-open if that doesn't fix it. 

Thanks for the awesome project.
