### ISSUE TITLE
Bind failed: Address already in use if file was created by TemporaryFolder rule

### ISSUE THREAD

**Issue by longtimeago** [jnr/jnr-unixsocket#16]
Good day!
Trying to use one of examples in unit test.
``` java
public class FrontTest {
    @Rule
    public final transient TemporaryFolder folder = new TemporaryFolder();

    @Test
    public void testRun() throws Exception {
        // File path = this.folder.newFile("fubar.sock");  // 1
        File path = new File("/tmp/fubar.sock");  // 2
        path.deleteOnExit();
        UnixSocketAddress address = new UnixSocketAddress(path);
        UnixServerSocketChannel channel = UnixServerSocketChannel.open();

        Selector sel = NativeSelectorProvider.getInstance().openSelector();
        channel.configureBlocking(false);
        channel.socket().bind(address);  // 3
   }
}
```
So, if file is created by line 2 - all is fine, no exceptions.
If I comment line 2 and uncomment line 1 there is and exception on line 3
```java
java.io.IOException: bind failed: Address already in use
	at jnr.unixsocket.UnixServerSocket.bind(UnixServerSocket.java:53)
	at jnr.unixsocket.UnixServerSocket.bind(UnixServerSocket.java:43)
	at foo.bar.FrontTest.testRun(FrontTest.java:51)
```
Do I miss something important?

Thank you!

**Comment by headius** [comment]
The file needs to be new for the server, or it will give you this error. If our tests don't do that, they should...and we'd appreciate a PR :-)
