### ISSUE TITLE
Support for ppc64le

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [jnr/jnr-unixsocket#74]
I am using jnr-unixsocket version: 0.22 
 jnr-ffi', version: '2.1.5'. 

when i run my project on ppc64le environment I get an error for unsupported architecture.

Error:-
Unhandled architecture/OS: ppc64le-Linux
	at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)

Can you please point me to the appropriate versions.

**Comment by headius** [comment]
The latest jnr-ffi is 2.1.10, which depends on jffi 1.2.19, which *should* work on ppcle Linux. Can you check if that one works?

**Comment by headius** [comment]
jnr-unixsocket 0.23 depends on jnr-ffi 2.1.10...

**Comment by rashmi-sakhalkar** [comment]
group: 'com.github.jnr', name: 'jnr-unixsocket', version: '0.23'
group: 'com.github.jnr', name: 'jnr-ffi', version: '2.1.10'
group: 'com.github.jnr', name: 'jffi', version: '1.2.19'

I updated the version values as shown above but I still get the same error. 

Error during callback
java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)


Caused by: java.lang.RuntimeException: Unhandled architecture/OS: ppc64le-Linux
	at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:30)

**Comment by headius** [comment]
That doesn't look like our error...I don't see that text anywhere in the JNR-projects.
