### ISSUE TITLE
 Found interface org.objectweb.asm.ClassVisitor, but class was expected 

### ISSUE THREAD

**Issue by lorna1** [jnr/jnr-unixsocket#86]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.ClassVisitor, but class was expected
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:101)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:86)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:392)

**Comment by lorna1** [comment]
asm:asm.jar 3.1
ow2.asm 7.1

**Comment by headius** [comment]
This would be an incompatibility in https://github.com/jnr/jnr-ffi with the very old ASM version you are using. You will want those versions to match and be more recent.
