### ISSUE TITLE
UnixClient fails sporadically on Darwin

### ISSUE THREAD

**Issue by headius** [jnr/jnr-unixsocket#96]
The example `UnixClient` appears to fail sporadically on Darwin. This frequently happens during release builds, but exactly once followed by a success. It could be a simple filesystem cleanup issue.

https://github.com/jnr/jnr-unixsocket/blob/f61210a4aff96058dc7c0d4e003ef1e810679e4f/src/test/java/jnr/unixsocket/example/UnixClient.java#L46

```
    [INFO] --- exec-maven-plugin:1.4.0:exec (execute) @ jnr-unixsocket ---
    Exception in thread "main" java.io.IOException: No such file or directory
    	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:130)
    	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:139)
    	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:68)
    	at jnr.unixsocket.example.UnixClient.main(UnixClient.java:46)
```

**Comment by headius** [comment]
Note this is not to be confused with the example `UnixClient` in #93.
